openapi: 3.0.1
info:
  title: Weavile Api
  version: 1.0.0
servers:
- url: http://localhost:9002
- url: https://www.weavileteambuilder.com/
tags:
- name: Item
  description: Endpoints related to item data
- name: Nature
  description: Endpoints related to pokemon natures
- name: CRUD Pokemon Teams
  description: Endpoints related to Pokemon Teams CRUD actions
- name: Pokemon Data
  description: Endpoints to return all relevant data about pokemon
paths:
  /nonLoggedUsers/pokemonTeam/createNewTeam:
    post:
      tags:
      - CRUD Pokemon Teams
      summary: Create a new pokemon team
      description: Requests to create a new pokemon team. Will retrieve an empty team
        if succesfull
      operationId: createNewTeam
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "201":
          description: Returns an empty pokemon team
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PokemonTeam"
  /pokemonData/getPokemonByName/{name}:
    get:
      tags:
      - Pokemon Data
      summary: Get pokemonData by name
      description: Request a certain pokemonData by name
      operationId: getPokemonByName
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: There are not any entities that match the parameter given
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Succesfully retrieved pokemon
  /pokemonData/allSVPokemon:
    get:
      tags:
      - Pokemon Data
      summary: Retrieve all available pokemon in sv
      description: Returns a list of pokemon data which are available in pokemon sv
      operationId: allSVPokemon
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Successful request with all pokemon data
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PokemonData"
  /natureData/getNatureByName/{name}:
    get:
      tags:
      - Nature
      summary: Get a nature by name parameter
      description: Returns a nature based on string parameter
      operationId: getNatureByName
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: There are not any entities that match the parameter given
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Nature successfully retrieved
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/NatureData"
  /natureData/getAllNatures:
    get:
      tags:
      - Nature
      summary: Get all natures
      description: Get a list with all pokemon natures
      operationId: getAllNatures
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Nature list successfully retrieved
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NatureData"
  /itemData/getItemByName/{itemName}:
    get:
      tags:
      - Item
      summary: Get item by name
      description: Returns an item using an string as parameter
      operationId: getItemByName
      parameters:
      - name: itemName
        in: path
        description: The item name to search
        required: true
        schema:
          type: string
        example: Choice Band
      responses:
        "404":
          description: There are not any entities that match the parameter given
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Item succesfully obtained
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ItemDto"
  /itemData/allItems:
    get:
      tags:
      - Item
      summary: Get all items
      description: Returns a list with all items
      operationId: getAllItems
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WeavileErrorResponse"
        "200":
          description: Items successfully retrieved
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemDto"
components:
  schemas:
    WeavileErrorResponse:
      type: object
      properties:
        message:
          type: string
        date:
          type: string
          format: date
    AbilityData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        pokemon_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonData"
        pokemon_team_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonTeamMember"
    ItemData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        image_sprite:
          type: string
          format: byte
        name:
          type: string
        description:
          type: string
    MoveData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        move_type:
          type: string
          enum:
          - PHYSICAL
          - SPECIAL
          - STATUS
        power:
          type: integer
          format: int32
        accuracy:
          type: integer
          format: int32
        description:
          type: string
        pp:
          type: integer
          format: int32
        pokemon_type:
          $ref: "#/components/schemas/PokemonType"
        pokemon_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonData"
        pokemon_team_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonTeamMember"
    NatureData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        increased_stat:
          type: string
        decreased_stat:
          type: string
    PokemonData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        base_hp:
          type: integer
          format: int32
        base_attack:
          type: integer
          format: int32
        base_defense:
          type: integer
          format: int32
        base_special_attack:
          type: integer
          format: int32
        base_special_defense:
          type: integer
          format: int32
        base_speed:
          type: integer
          format: int32
        front_default_sprite:
          type: string
          format: byte
        pc_sprite:
          type: string
          format: byte
        type_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonType"
        ability_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/AbilityData"
        move_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/MoveData"
        availableInSv:
          type: boolean
    PokemonTeam:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        teamType:
          type: string
          enum:
          - "0"
          - "1"
          - "2"
          - "3"
          - "4"
        teamMembers:
          type: array
          items:
            $ref: "#/components/schemas/PokemonTeamMember"
        teamSize:
          type: integer
          format: int32
          writeOnly: true
    PokemonTeamMember:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        front_default_sprite:
          type: string
          format: byte
        pc_sprite:
          type: string
          format: byte
        base_hp:
          type: integer
          format: int32
        base_attack:
          type: integer
          format: int32
        base_defense:
          type: integer
          format: int32
        base_special_attack:
          type: integer
          format: int32
        base_special_defense:
          type: integer
          format: int32
        base_speed:
          type: integer
          format: int32
        hp_ev:
          type: integer
          format: int32
        attack_ev:
          type: integer
          format: int32
        defense_ev:
          type: integer
          format: int32
        special_attack_ev:
          type: integer
          format: int32
        special_defense_ev:
          type: integer
          format: int32
        speed_ev:
          type: integer
          format: int32
        hp_iv:
          type: integer
          format: int32
        attack_iv:
          type: integer
          format: int32
        defense_iv:
          type: integer
          format: int32
        special_attack_iv:
          type: integer
          format: int32
        special_defense_iv:
          type: integer
          format: int32
        speed_iv:
          type: integer
          format: int32
        move_list:
          maxItems: 4
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/MoveData"
        ability:
          $ref: "#/components/schemas/AbilityData"
        item:
          $ref: "#/components/schemas/ItemData"
        team_member_type_list:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/PokemonType"
        tera_type:
          $ref: "#/components/schemas/PokemonType"
        nature:
          $ref: "#/components/schemas/NatureData"
    PokemonType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        sprite:
          type: string
          format: byte
    ItemDto:
      type: object
      properties:
        image_sprite:
          type: string
          format: byte
        name:
          type: string
        description:
          type: string
