/* tslint:disable */
/* eslint-disable */
/**
 * Weavile Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { RequestArgs } from './base';
import { DUMMY_BASE_URL, assertParamExists, createRequestFunction, setSearchParams, toPathString } from './common';
// @ts-ignore
import { ItemDto } from '../src/domain/dataEntities';
import { NatureDto } from '../src/domain/teamMemberEntities/NatureDto';
import { PokemonTeam } from '../src/domain/teamMemberEntities/PokemonTeam';
import { BASE_PATH, BaseAPI, RequiredError, operationServerMap } from './base';


/**
 * CRUDPokemonTeamsApi - axios parameter creator
 */
export const CRUDPokemonTeamsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Requests to create a new pokemon team. Will retrieve an empty team if succesfull
         * @summary Create a new pokemon team
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewTeam: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/nonLoggedUsers/pokemonTeam/createNewTeam`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CRUDPokemonTeamsApi - functional programming interface
 */
export const CRUDPokemonTeamsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CRUDPokemonTeamsApiAxiosParamCreator(configuration)
    return {
        /**
         * Requests to create a new pokemon team. Will retrieve an empty team if succesfull
         * @summary Create a new pokemon team
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewTeam(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PokemonTeam>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewTeam(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CRUDPokemonTeamsApi.createNewTeam']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CRUDPokemonTeamsApi - factory interface
 */
export const CRUDPokemonTeamsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CRUDPokemonTeamsApiFp(configuration)
    return {
        /**
         * Requests to create a new pokemon team. Will retrieve an empty team if succesfull
         * @summary Create a new pokemon team
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewTeam(options?: RawAxiosRequestConfig): AxiosPromise<PokemonTeam> {
            return localVarFp.createNewTeam(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CRUDPokemonTeamsApi - object-oriented interface
 */
export class CRUDPokemonTeamsApi extends BaseAPI {
    /**
     * Requests to create a new pokemon team. Will retrieve an empty team if succesfull
     * @summary Create a new pokemon team
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNewTeam(options?: RawAxiosRequestConfig) {
        return CRUDPokemonTeamsApiFp(this.configuration).createNewTeam(options).then((request) => request(this.axios, this.basePath));
    }
}





/**
 * NatureApi - axios parameter creator
 */
export const NatureApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list with all pokemon natures
         * @summary Get all natures
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNatures: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/natureData/getAllNatures`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a nature based on string parameter
         * @summary Get a nature by name parameter
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNatureByName: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getNatureByName', 'name', name)
            const localVarPath = `/natureData/getNatureByName/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NatureApi - functional programming interface
 */
export const NatureApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NatureApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a list with all pokemon natures
         * @summary Get all natures
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllNatures(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NatureDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllNatures(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NatureApi.getAllNatures']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a nature based on string parameter
         * @summary Get a nature by name parameter
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNatureByName(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NatureDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNatureByName(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NatureApi.getNatureByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NatureApi - factory interface
 */
export const NatureApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NatureApiFp(configuration)
    return {
        /**
         * Get a list with all pokemon natures
         * @summary Get all natures
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNatures(options?: RawAxiosRequestConfig): AxiosPromise<Array<NatureDto>> {
            return localVarFp.getAllNatures(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a nature based on string parameter
         * @summary Get a nature by name parameter
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNatureByName(name: string, options?: RawAxiosRequestConfig): AxiosPromise<NatureDto> {
            return localVarFp.getNatureByName(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NatureApi - object-oriented interface
 */
export class NatureApi extends BaseAPI {
    /**
     * Get a list with all pokemon natures
     * @summary Get all natures
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllNatures(options?: RawAxiosRequestConfig) {
        return NatureApiFp(this.configuration).getAllNatures(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a nature based on string parameter
     * @summary Get a nature by name parameter
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNatureByName(name: string, options?: RawAxiosRequestConfig) {
        return NatureApiFp(this.configuration).getNatureByName(name, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PokemonDataApi - axios parameter creator
 */
export const PokemonDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a list of pokemon data which are available in pokemon sv
         * @summary Retrieve all available pokemon in sv
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allSVPokemon: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pokemonData/allSVPokemon`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Request a certain pokemonData by name
         * @summary Get pokemonData by name
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPokemonByName: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getPokemonByName', 'name', name)
            const localVarPath = `/pokemonData/getPokemonByName/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PokemonDataApi - functional programming interface
 */
export const PokemonDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PokemonDataApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a list of pokemon data which are available in pokemon sv
         * @summary Retrieve all available pokemon in sv
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allSVPokemon(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PokemonDataApi>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.allSVPokemon(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PokemonDataApi.allSVPokemon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Request a certain pokemonData by name
         * @summary Get pokemonData by name
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPokemonByName(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPokemonByName(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PokemonDataApi.getPokemonByName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PokemonDataApi - factory interface
 */
export const PokemonDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PokemonDataApiFp(configuration)
    return {
        /**
         * Returns a list of pokemon data which are available in pokemon sv
         * @summary Retrieve all available pokemon in sv
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allSVPokemon(options?: RawAxiosRequestConfig): AxiosPromise<Array<PokemonDataApi>> {
            return localVarFp.allSVPokemon(options).then((request) => request(axios, basePath));
        },
        /**
         * Request a certain pokemonData by name
         * @summary Get pokemonData by name
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPokemonByName(name: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getPokemonByName(name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PokemonDataApi - object-oriented interface
 */
export class PokemonDataApi extends BaseAPI {
    /**
     * Returns a list of pokemon data which are available in pokemon sv
     * @summary Retrieve all available pokemon in sv
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public allSVPokemon(options?: RawAxiosRequestConfig) {
        return PokemonDataApiFp(this.configuration).allSVPokemon(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Request a certain pokemonData by name
     * @summary Get pokemonData by name
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPokemonByName(name: string, options?: RawAxiosRequestConfig) {
        return PokemonDataApiFp(this.configuration).getPokemonByName(name, options).then((request) => request(this.axios, this.basePath));
    }
}



